# Generated by Django 4.2.20 on 2025-03-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=100)),
                ('dob', models.CharField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
    ]
