# Generated by Django 4.2.20 on 2025-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
